repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
